



export const metadata = {
    title: 'DashBoard || me ',
    description: 'Generated by create next app',
  }

const me = () => {
    return (
        <div>
            hi i am me


            <a href="/Dashboard" className="py-3 px-4 border-2">Dashboard</a>


        </div>
    );
};

export default me;